### ISSUE TITLE
Keyboard shortcuts?

### ISSUE THREAD

**Issue by jcf-junior** [rshev/MoveTabToNextWindow#21]
Hello, 

Despite the app featuring keyboard shortcut support, there is no mention of the default keyboard shortcut anywhere in this repo, nor is there a mention on the extension's Chrome Store page.

If there is no default shortcut, is there a way for users to set their own?

**Comment by rshev** [comment]
There is no default shortcut, but you can set one in Extensions->Keyboard shortcuts:
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/c88a131c-5028-4898-81b1-3cc355aba3c2">

**Comment by jcf-junior** [comment]
Thank you so much for your fast response
