### ISSUE TITLE
[feature request] Adding a keyboard shortcut

### ISSUE THREAD

**Issue by m3at** [rshev/MoveTabToNextWindow#6]
This extension is neat, thank you! It's simple and does one job well.

Do you think it would be possible to add a shortcut as well?

**Comment by rshev** [comment]
Thank you for the kind words! Keyboard shortcuts should be easy to add, I'll take a look!

**Comment by rshev** [comment]
Added keyboard shortcut into 1.1.0, it's already in store for Firefox, will be available shortly for Chrome and Edge!

**Comment by m3at** [comment]
Awesome! Many thanks
